#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

target:
  aux:
    global_centering: false
    scale_init: 0.1
    trainable_augmented_scale: false

flow:
  n_aug: 1
  base:
    train_x_scale: true
    x_scale_init: 1.0
    aux:
      global_centering: false
      scale_init: ${target.aux.scale_init}
      trainable_augmented_scale: true
  dim: 3
  nodes: 19
  n_layers: 8
  identity_init: true
  type: vector_proj #  nice proj_rnvp  proj_spline
  kwargs:
    vector_proj:
      transform_type: real_nvp
      n_vectors: 3
      spline_num_bins: 5
      spline_max: 10.
    proj_rnvp:
      origin_on_coupled_pair: false
    proj_spline:
      origin_on_coupled_pair: false
      num_bins: 8
      lower: -2.
      upper: 2.
  act_norm: false
  compile_n_unroll: 1
  nets:
    type: egnn
    egnn:
      name: egnn
      n_blocks: 3 # number of layers
      mlp_units: [ 128, 128 ]
      n_invariant_feat_hidden: 128
      cross_multiplicity_shifts: false
    e3gnn:
      name: e3gnn
      n_blocks: 3 # number of layers
      mlp_units: [128, 128]
      n_vectors_hidden_per_vec_in: 4
      n_invariant_feat_hidden: 128
      get_shifts_via_tensor_product: false
    mlp_head_config:
      mlp_units: [ 128, 128 ]


training:
  optimizer:
    init_lr: 1e-4
    optimizer_name: adam
    use_schedule: true
    peak_lr: 6e-4
    end_lr: 1e-4 # can be null
    warmup_n_epoch: 10 # can be null
    max_global_norm: 1.0
  use_64_bit: false
  n_epoch: 64
  batch_size: 32
  plot_batch_size: 128
  seed: 0
  train_set_size: null
  test_set_size: null
  n_checkpoints: 0
  n_eval: 15
  K_marginal_log_lik: 20
  save: true
  save_dir: qm9pos_results
  resume: false
  runtime_limit: null
  use_flow_aux_loss: true
  aux_loss_weight: 10.0
  last_iter_info_only: true
  debug: false

logger:
#  list_logger: null
#  pandas_logger:
#    save_period: 1000 # how often to save the pandas dataframe as a csv
  wandb:
    name: qm9pos_${flow.type}_${flow.nets.type}_auxloss${training.use_flow_aux_loss}_bs${training.batch_size}_naug${flow.n_aug}_trainabletarg${target.aux.trainable_augmented_scale}_fat # qm9pos_${flow.type}_${flow.nets.type}_batchsize${training.batch_size}_opt${training.optimizer.optimizer_name}_maxnorm${training.optimizer.max_global_norm}_lrs${training.optimizer.init_lr}-${training.optimizer.peak_lr}_layers${flow.n_layers}_augtargetscale${target.aug_scale}
    project: fab
    entity: flow-ais-bootstrap
    tags: [qm9pos,loll]
