#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

target:
  aug_global_centering: false
  aug_scale: 0.1

flow:
  base:
    aug_scale_init: ${target.aug_scale}
    double_centered_gaussian: false
  dim: 3
  nodes: 19
  n_layers: 10
  identity_init: true
  type: [proj,]  # vector_scale_shift  vector_scale nice proj
  act_norm: false
  kwargs:
    proj:
      global_frame: false
      process_flow_params_jointly: false
      condition_on_x_proj: true
      gram_schmidt: false
    proj_v2:
      process_flow_params_jointly: false
      condition_on_x_proj: true
      gram_schmidt: false
      n_vectors: 10
  fast_compile: true
  compile_n_unroll: 1
  nets:
    use_mace: true
    mace:
      n_invariant_feat_hidden: 64
      n_vectors_hidden: 16
      bessel_number: 10  # Number of bessel functions.
      r_max: 10.
      n_interactions: 2
      interaction_irreps: o3_restricted  # "o3_restricted",  # or o3_full
    egnn:
      mlp_units: [64,64]
      n_layers: 3
      normalize_by_norms: true
      variance_scaling_init: 0.001
      tanh: false
      agg: mean
      phi_x_max: 1.0
      normalization_constant: 1.0
      h_linear_softmax: true
      h_embedding_dim: 64
    transformer: # for proj flow
      mlp_units: [64,64]
      num_heads: 6
      key_size: 16
      w_init_scale: 0.1
      n_layers: 3
    mlp_head_config:
      mlp_units: [ 64, 64 ]


training:
  optimizer:
    init_lr: 1e-5
    optimizer_name: adam
    use_schedule: true
    peak_lr: 2e-4 # can be null
    end_lr: 1e-6 # can be null
    warmup_n_epoch: 10 # can be null
    max_global_norm: 0.25
  use_64_bit: false
  n_epoch: 64
  batch_size: 64
  plot_batch_size: 64
  seed: 0
  reload_aug_per_epoch: true
  train_set_size: null
  test_set_size: null
  n_plots: 20
  n_checkpoints: 0
  n_eval: 20
  K_marginal_log_lik: 20
  save: true
  save_dir: qm9pos_results

logger:
#  list_logger: null
  wandb:
    name: qm9pos_${flow.type}_batchsize${training.batch_size}_opt${training.optimizer.optimizer_name}_maxnorm${training.optimizer.max_global_norm}_lrs${training.optimizer.init_lr}-${training.optimizer.peak_lr}_layers${flow.n_layers}_augtargetscale${target.aug_scale}
    project: fab
    entity: flow-ais-bootstrap
    tags: [qm9pos,loll]