#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

target:
  aux:
    conditioned_on_x: true
    scale_init: 1.0
    trainable_augmented_scale: false

flow:
  n_aug: 3
  act_norm: false
  base:
    x_dist:
      type: centre_gravity_gaussian
    aux:
      conditioned_on_x: ${target.aux.conditioned_on_x}
      scale_init: ${target.aux.scale_init}
      trainable_augmented_scale: false
  dim: 3
  nodes: 19
  n_layers: 8
  identity_init: true
  type: along_vector #  nice proj spherical along_vector
  kwargs:
    n_inner_transforms: 2
    along_vector:
      n_inner_transforms: ${flow.kwargs.n_inner_transforms}
      dist_spline_max: 10.
      spline_num_bins: 8
    spherical:
      n_inner_transforms: ${flow.kwargs.n_inner_transforms}
      dist_spline_max: 10.
      spline_num_bins: 8
    proj:
      transform_type: spline # spline or real_nvp
      n_inner_transforms: ${flow.kwargs.n_inner_transforms}
      origin_on_coupled_pair: false
      num_bins: 8
      lower: -10.
      upper: 10.
      orthogonalization_method: gram-schmidt   #  gram-schmidt or loewdin
  nets:
    type: egnn
    egnn:
      name: egnn
      n_blocks: 3 # number of layers
      mlp_units: [ 64, 64 ]
      n_invariant_feat_hidden: 64
      cross_multiplicity_shifts: true
    e3gnn:
      name: e3gnn
      n_blocks: 3 # number of layers
      mlp_units: [64, 64]
      n_vectors_hidden_per_vec_in: 4
      n_invariant_feat_hidden: 64
      get_shifts_via_tensor_product: false
    mlp_head_config:
      mlp_units: [64, 64]
      stable: true


training:
  optimizer:
    init_lr: 1e-4
    optimizer_name: adam
    use_schedule: true
    peak_lr: 3e-4
    end_lr: 6e-5 # can be null
    warmup_n_epoch: 10 # can be null
    max_global_norm: null
    max_param_grad: null
    dynamic_grad_ignore_and_clip: true
  use_64_bit: false
  n_epoch: 64
  batch_size: 32
  plot_batch_size: 128
  eval_batch_size: 128
  seed: 0
  train_set_size: null
  test_set_size: null
  n_checkpoints: 0
  n_eval: 15
  K_marginal_log_lik: 20
  save: true
  save_dir: qm9pos_results
  resume: false
  runtime_limit: null
  use_flow_aux_loss: true
  aux_loss_weight: 10.0
  last_iter_info_only: true
  debug: false

logger:
#  list_logger: null
#  pandas_logger:
#    save_period: 1000 # how often to save the pandas dataframe as a csv
  wandb:
    name: qm9pos_${flow.type}_${flow.nets.type}_AUG${flow.n_aug}_InnerTransforms${flow.kwargs.n_inner_transforms}_actnorm${flow.act_norm}
    project: fab
    entity: flow-ais-bootstrap
    tags: [qm9pos,loll]
