#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

target:
  aug_global_centering: false
  aug_scale: 0.1

flow:
  base:
    aug_scale_init: ${target.aug_scale}
    double_centrered_gaussian: false
  dim: 3
  nodes: 19
  n_layers: 12
  identity_init: true
  type: [proj,]  # vector_scale_shift  vector_scale nice proj
  act_norm: false
  kwargs:
    proj:
      global_frame: false
      process_flow_params_jointly: false
      condition_on_x_proj: true
      gram_schmidt: false
      mlp_function_units: [64,64]
    proj_v2:
      process_flow_params_jointly: false
      condition_on_x_proj: true
      gram_schmidt: false
      mlp_function_units: [ 64,64 ]
  fast_compile: true
  compile_n_unroll: 1
  egnn:
    emile_net: false
    mlp_units: [64,64]
    n_layers: 3
    normalize_by_norms: true
    variance_scaling_init: 0.001
    tanh: false
    agg: mean
    phi_x_max: 1.0
    normalization_constant: 1.0
    h:
      linear_softmax: true
      h_embedding_dim: 64
  transformer: # for proj flow
    mlp_units: [64,64]
    num_heads: 6
    key_size: 16
    w_init_scale: 0.1
    n_layers: 3


training:
  lr: 6e-5
  use_64_bit: false
  optimizer_name: adamw
  n_epoch: 800
  batch_size: 64
  plot_batch_size: 64
  max_global_norm: 12_000
  seed: 0
  reload_aug_per_epoch: true
  train_set_size: null
  test_set_size: null
  n_plots: 10
  n_checkpoints: 0
  n_eval: 12
  K_marginal_log_lik: 20
  save: true
  save_dir: qm9pos_results

logger:
#  list_logger: null
  wandb:
    name: qm9pos_${flow.type}_batchsize${training.batch_size}_lr${training.lr}_layers${flow.n_layers}_augtargetscale${target.aug_scale}_opt${training.optimizer_name}
    project: fab
    entity: flow-ais-bootstrap
    tags: [qm9pos,loll]